services:
  - postgresql

language: "python"
python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
before_script:
  - — psql -c “CREATE USER postgres WITH PASSWORD postgres;” -U
script:
  - pytest --cov=ublox_reader tests