sudo: true

services:
  - postgresql

language: "python"
python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
   - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
   - sudo service postgresql restart

script:
  - pytest --cov=ublox_reader tests