sudo: true

services:
  - postgresql

language: "python"
python:
  - "3.7"
  - "3.8"

before_install:
  - sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres'"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=ublox_reader tests