sudo: true

services:
  - postgresql

language: "python"
python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - cp tests/database.yml.travis config/database.yml


script:
  - pytest --cov=ublox_reader tests