sudo: true

services:
  - postgresql

language: "python"
python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

before_script:
  - pwd
  - mkdir config && cp tests/database.travis.yml config/database.yml

script:
  - pytest --cov=ublox_reader tests