site_name: GoEasy

theme:
  name: material
  palette:
    primary: blue
    accent: amber
  language: en
  logo: img/satellite.png
  favicon: img/satellite.png

nav:
  - GoEasy: index.md
  - U-blox API:
      - u-blox api/features.md
      - u-blox api/deployment.md
  - U-blox Reader:
      - u-blox reader/features.md
      - u-blox reader/deployment.md
  - Serengeti:
      - serengeti/features.md
      - serengeti/deployment.md